# Generated by Django 3.2.3 on 2021-05-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('modify_own_author', 'Can change their own author settings and visibilty status')]},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on'], 'permissions': [('create_own_post', 'Can create a new post with themselves as the author')]},
        ),
    ]
