# Generated by Django 3.2.3 on 2021-05-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210520_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
