# Generated by Django 3.2.3 on 2021-05-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_header_image_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('delete_comments_on_own_post', 'Can delete any comment left on a post they created')]},
        ),
    ]
