# Generated by Django 3.2.3 on 2021-06-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210602_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('nc', 'New comment'), ('pm', 'Private message')], default='nc', max_length=2),
            preserve_default=False,
        ),
    ]
