# Generated by Django 3.2.3 on 2021-06-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
