# Generated by Django 3.2.3 on 2021-06-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_privatemessage_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatemessage',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
